spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:redlix/verb/config.git
          username: 405149812@qq.com
          password: lxh1530675447
          basedir: /home/workspace/JavaWeb/verb/config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"